### ISSUE TITLE
Designer Of Beautiful Things

### ISSUE THREAD

**Issue by NothingEverHappens** [AngularNYC/meetup#146]
Make sure things look beautiful

# Time commitment:
2-3 hours. 

## Role description

- [ ] Create 2-3 pictures with meetup info, which would look good in social media

When a new speaker is added
- [ ] Update the picture
- [ ] Send the picture to the Event host (or maybe just become an event host and upload it)

Bonus
- [ ] Find of more ways to make the things beautiful

## Sample picture (you can probably do better)

![image](https://cloud.githubusercontent.com/assets/2545357/26615336/0900e044-4594-11e7-8e20-ad216634cb03.png)

**Comment by DanBotero** [comment]
@missuze do we have any images for this event? I would like to have them to post them on our Facebook account. Thanks!

**Comment by kirjs** [comment]
Ok, this didn't really work out
