### ISSUE TITLE
Event Host on meetup.com

### ISSUE THREAD

**Issue by NothingEverHappens** [AngularNYC/meetup#148]
## Requirements
Be available to change things quickly, and do everything as early as possible

## Time commitment
2-3 hours,
needs to be continuously available to make updates.

## Role description
Creating the event: 
- [x] Ask @kirjs to add you as an event host for the event on the meetup.com
- [x] Add event information to the event: 
- [x] Add the correct location
- [x] Make sure that the map is displayed correctly on **iPhone** (meetup has a known bug with directing people to a random point on the map)
- [x] Make sure that the map is displayed correctly on **Android**
- [x] Add a generic schedule, make sure schedule is up-to-date
- [x] Make sure there's there's a mention of full name and ID being required.
- [ ] Work together with designer to make sure everything is beautiful.

**Comment by Nehal90** [comment]
@kirjs If most of the work can be done remotely, I can pickup this task :)

**Comment by tessaSAC** [comment]
Hey Nehal, I added the location :)

**Comment by tessaSAC** [comment]
Hey Ahmed, I added the location :)

**Comment by Nehal90** [comment]
@tessaSAC  Thank you Tessa. I verified the address points to right location in Iphone/Apple Maps.

**Comment by tessaSAC** [comment]
Cool! Were you the one who checked Android too?

Do you think you can add the basic description/schedule and announce the meetup within the next couple days? :)

**Comment by kirjs** [comment]
I checked android :)

**Comment by Nehal90** [comment]
@tessaSAC Yep, just waiting on details of both speakers' topics. I'll work with Kirill on that.
@kirjs Thank you :)

**Comment by tessaSAC** [comment]
Great Ahmed! I think we have one of the speakers confirmed now, right?

**Comment by Nehal90** [comment]
@tessaSAC @kirjs Hi guys, I created this initial draft.

I took the agenda template from June 12 meetup. There are couple of lightening talks scheduled, not really sure how to format them in the agenda. Would love some help/guidance from you guys.

Please give your feedback or edit if you'd like to.

6:00 - Food and chat

6:15 - Talk: Torgeir Helgevold - Angular in production

6:45 - Break

7:00 - Lightning talks TBD

IMPORTANT: Please use your FULL REAL NAME and bring your ID. 

### Talks:

# Angular in production

![26909946-0cefc5d2-4bd2-11e7-914b-54017d0a5696](https://user-images.githubusercontent.com/12707199/26941580-f7cd29e4-4c4c-11e7-9e76-6e8701387fa7.jpg)

by **Torgeir Helgevold** [@helgevold](https://twitter.com/helgevold)

Torgeir will talk about different approaches that can be used to optimize Angular production builds. He will show examples and demo as well as discuss pros and cons of each method.

**Comment by kirjs** [comment]
I edited the draft, please post this and announce the meetup.
Also lightning talks are for a different event

**Comment by Nehal90** [comment]
Ok, I'll remove the lightening talks :)

**Comment by Nehal90** [comment]
@kirjs I posted the agenda but need help with 'Announcement'. 

Meetup doc says, 

> You'll also see an 'Announce now' button on the Meetup event page up until 7 days before the Meetup is scheduled to take place.

I can't find that button :( unless it's already been announced.

**Comment by kirjs** [comment]
I just announced it, thanks @Nehal90!

**Comment by tessaSAC** [comment]
![](https://cdn.discordapp.com/attachments/319344608477839360/322946578908315648/AngularNYC-torgeir.png)

**Comment by Nehal90** [comment]
Hi @tessaSAC , what do we need to do to finish the last task "Work together with designer to make sure everything is beautiful?"  Then we can close this one 💃

**Comment by kirjs** [comment]
Let's consider it done @Nehal90, designer thing didn't really work out for this specific event :)

**Comment by Nehal90** [comment]
Ok, closing it then :)
