### ISSUE TITLE
Create a slidedeck

### ISSUE THREAD

**Issue by NothingEverHappens** [AngularNYC/meetup#151]
# Time commitment 
2 hours before the event

# Role description
- [x] Clone [Sample Slide Deck](https://docs.google.com/presentation/d/1Sld3KtITtskk1FlfqIdMYHFEE-koByksOJ0YvnzQNnw/edit#slide=id.g1387209594_2_1)
- [x] Post the link in the comments and mention @kirjs
- [x] Make sure event title and date is correct
- [x] Make sure correct wifi network is displayed
- [x] Make sure each sponsor has a slide
- [x] Update the list of organizers (this may be tricky, use task assignees and slack chat room to get photos and names of everybody involved in this meetup)
- [x] Confirm raffle link works
- [x] Make sure every speaker has their own slide (create a placeholder and share give edit access to all speaker coordinators)
- [x] Confirm with @kirjs if there is anything special going on that needs a slide
- [x] When everything is ready - post a view only link on meetup.com (or send it to event host)

**Comment by kirjs** [comment]
Slide deck for June meetup: https://docs.google.com/presentation/d/1VYIVbJ9871NPM052tS88Lg9c2vhdXmBb1mkHOWgHN98/edit#slide=id.g1387209594_0_5
