### ISSUE TITLE
Come up with a fun activity which is not a talk [Event experience]

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/meetup#152]
# Time commitment 
1 hour

# Role description
- [x] Get a bunch of organizers in one slack chat room together
- [x] Make sure they brainstorm until there's a good option
- [x] Post the results here

**Comment by sunilj74** [comment]
If you can get someone to donate some small gifts or something, then we can tape it under some chairs. Then before the meetup starts or before a break we could ask people to look for a surprise.

**Comment by tessaSAC** [comment]
Can this be a time to try the werewolf?
