### ISSUE TITLE
Create a google calendar invite

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/meetup#166]
# Time commitment
30 minutes

# Role description
- [x] Create a google calendar invite
- [x] Send it to the organizers
- [ ] Send it to speakers

Need to figure out how to find everybody's emails and how to scale it in the future

**Comment by tessaSAC** [comment]
Maybe you can make a meetup calendar and people just get added to that calendar? (and then they can remove it after if they're a speaker and don't want it anymore) What do you think @kirjs

**Comment by bruno78** [comment]
That's a good idea. I'm fine either way. It's up to you @kirjs! What do I need to do to set up the google calendar invite?
