### ISSUE TITLE
Designer Of Beautiful Things

### ISSUE THREAD

**Issue by bruno78** [AngularNYC/meetup#174]
Make sure things look beautiful

# Time commitment:
2-3 hours. 

## Role description

- [x] Create 2-3 pictures with meetup info, which would look good in social media

When a new speaker is added
- [x] Update the picture
- [x] Send the picture to the Event host (or maybe just become an event host and upload it)

Bonus
- [ ] Find of more ways to make the things beautiful

## Sample picture (you can probably do better)

![image](https://cloud.githubusercontent.com/assets/2545357/26615336/0900e044-4594-11e7-8e20-ad216634cb03.png)

**Comment by barlanj** [comment]
I'll attempt this for the coming meetup.

Do we have a place where images are stored for meetups? google drive? dropbox?

**Comment by kirjs** [comment]
I though this turned out really nice
<img width="526" alt="screen shot 2017-07-04 at 1 02 12 am" src="https://user-images.githubusercontent.com/2545357/27808978-8450bef6-6054-11e7-8784-e56914baae8f.png">

**Comment by kirjs** [comment]
https://blog.bufferapp.com/ideal-image-sizes-social-media-posts

**Comment by tessaSAC** [comment]
How's this going @barlanj?
