### ISSUE TITLE
Event Host on meetup.com

### ISSUE THREAD

**Issue by bruno78** [AngularNYC/meetup#176]
## Requirements
Be available to change things quickly, and do everything as early as possible

## Time commitment
2-3 hours,
needs to be continuously available to make updates.

## Role description
Creating the event: 
- [x] Ask @kirjs to add you as an event host for the event on the meetup.com
- [x] Add event information to the event: 
- [x] Add the correct location
- [x] Make sure that the map is displayed correctly on **iPhone** (meetup has a known bug with directing people to a random point on the map)
- [x] Make sure that the map is displayed correctly on **Android**
- [x] Add a generic schedule, make sure schedule is up-to-date
- [x] Make sure there's there's a mention of full name and ID being required.
- [x] Work together with designer to make sure everything is beautiful.

**Comment by tessaSAC** [comment]
Adding @barlanj for when he prettifies stuff (fyi added Eudes' info to the meetup page and it's ready to be prettified... ✨)

**Comment by barlanj** [comment]
We should ask for hi-res pictures so we can crop/stretch as needed. I mean... everyone's phone is capable of this, no one should be giving grainy small images. lol

**Comment by tessaSAC** [comment]
Since we have the descriptions for at least two people can we announce the meetup soon?

**Comment by barlanj** [comment]
ill get you the prettified pictures/card tonight.

**Comment by tessaSAC** [comment]
Heyo, is everything beautiful and is the Android map working? ☆( ͡° ͜ʖ ͡°)
