### ISSUE TITLE
Post Event After Party

### ISSUE THREAD

**Issue by bruno78** [AngularNYC/meetup#178]
# Time commitment:
1 hour research before the event
1 hour after the event

# Role description
Before the event: 
- [x] Research bars or other places we can go to after event
- [x] Make sure it's spacious enough for 20+ people
During the event: 
- [x] Announce the location to everybody
After the event: 
- [x] Lead people to the location 
- [x] Represent the meetup at the after party (Be responsible for making sure there are no code of conduct breaches )

**Comment by tessaSAC** [comment]
Location is [The Wild Son](https://www.yelp.com/map/the-wild-son-new-york) and I've bookmarked a couple others we can try in the future if we don't like this place (but it seems coo)
