### ISSUE TITLE
Post photos to Instagram

### ISSUE THREAD

**Issue by bruno78** [AngularNYC/meetup#182]
Time commitment: 
Before the  event: 2 hours
During the event: 2 hours 

# Role description
before the event:
- [x] Get social media information (and old photos) and credentials from @kirjs
- [x] Post 1 photo
- [x] Post 2 photo
- [x] Post 3 photo
- [ ] Post 4 photo
- [ ] Post 5 photo
- [ ] Post 6 photo

During the event:
- [ ] Post post a bunch of photos on Instagram

**Comment by bruno78** [comment]
@UmaMoiseenko and/or @tessaSAC can you check and close this one?

**Comment by tessaSAC** [comment]
I actually don't have the credentials for this one, sorry!
