### ISSUE TITLE
Find better calendar for Meetup Events 

### ISSUE THREAD

**Issue by bruno78** [AngularNYC/meetup#189]
# Role Description 
Find a calendar where you can create Event/invites (like Facebook events), so people can join as attendees and they can add the event to their own calendars. 
 
- [ ] Find a calendar app or webpage
- [ ] Create the event
- [ ] Send it to the organizers
- [ ] Send it to the speakers

**Comment by tessaSAC** [comment]
Are we going to use the airtable thing or google calendar or...?? @ilyagelman @kirjs

**Comment by tessaSAC** [comment]
See comments on #177

**Comment by tessaSAC** [comment]
Ok we agreed on Google Calendar finally! 🎉 @bruno78 😂😂😂

**Comment by bruno78** [comment]
I. AM. IN. SHOCK! Ahahahah
